// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNYCTuRVpdiXQx3aBtgqhNFzhLD1HorOM',
    appId: '1:441285474094:android:ad287d3fbefeb225d76cbf',
    messagingSenderId: '441285474094',
    projectId: 'proyectoedumentor-123abc',
    storageBucket: 'proyectoedumentor-123abc.appspot.com',
  );
}